export enum BaseErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  ACCESS_TOKEN_EXPIRED = 'TOKEN_EXPIRED_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
  INVALID_USER_INPUT = 'INVALID_USER_INPUT',
  USER_NOT_VERIFIED_ERROR = 'USER_NOT_VERIFIED_ERROR',
}
